### ISSUE TITLE
Idea for floating windows

### ISSUE THREAD

**Issue by controversial** [jsbain/backend_pythonista#1]
I think it'd be neat to emulate what iOS 9's PiP does, where you can drag windows around, flick them off to the side, and **controls are hidden unless you tap**. This is a very clean and unobtrusive way to present a floating window in a way that **makes sense on a touch device**. If you'd like, I could try to open a PR tomorrow.

**Comment by jsbain** [comment]
While I agree this makes sense for non-interactive windows, I am not sure what the right approach should be for floating views which implement some level of touch in their content.  

For instance, for a tableview, how to distinguish between the intention to scroll and the intention to drag the window, or the intention to select a row vs show the hidden menu

One option would be to allow views to get first crack at the touch events, except for long press which would enter a special mode.  In that mode we would pop up a shield view underneath (to capture touch events outside of the floater), show a hidden menu overlay, and in that mode give the floating window priority over touch events:  menu taps run the associated action, , drag moves the window, corner drags resize.  Touching outside of the view would then lock it back in place and let the content get touches again.  of course this means content cannot implement longpress gestures. 
For views without touch handling, then one might want to forego the need for long press.

Another option might be to keep a dedicated title bar to use as a handle for dragging when the content implements touch,  but without controls.  Tapping the title would then show controls, similar to the way safari address bar works.

Yet another option might use two finger gestures to drag the window, two finger tap to show menu, etc, but that feels less discoverable.  

For matplotlib content specifically,  the window title, or at least the figure number is important info that should not be hidden, but could be much smaller.

**Comment by controversial** [comment]
We could have 2 options, one for non-interactive windoss and one for
interactive ones. I just think for the case of matplotlib charts, the view
could be vastly optimized since the plots don't need to be touch-sensitive.

**Comment by jsbain** [comment]
matplotlib plots will (eventually) be touch sensitive, although i am sort of debating whether it makes more sense to use the simple event system i started here, or making a separate custom view subclass.  The eventual plan would be that a matplotlib plot supports two finger pinch/zoom, one finger object selection then one finger drag to reposition things like selected text or legends.   Double tap for editing text strings.  Perhaps longpress data cursor, though perhaps a special mode makes more sense for cursor.

**Comment by controversial** [comment]
Ok. But by the time we're at this point, it doesn't make sense to have it
in a floating window anymore, presenting in a panel would be much more
realistic. Perhaps it could be fullscreen and then minimizable into a
floating window, at which point touch events would disappear?
